### ISSUE TITLE
Missing content directory from validation file

### ISSUE THREAD

**Issue by edbeeching** [facebookresearch/habitat-challenge#1]
It appears that the point task file _pointnav_gibson_v1.zip_  is missing the _content_ directory for the val environments. Or perhaps I am missing something.

Thanks for any assistance.

**Comment by abhiskk** [comment]
Your observation is correct. We support loading of the episodes split (the `.json.gz` files in 2 methods. One is using the content dir which is helpful in splitting the episodes across different processes, the second method is loading from the file.

We did have loading of the val split in the file: [`habitat-api/baselines/evaluate_ppo.py`](https://github.com/facebookresearch/habitat-api/blob/master/baselines/evaluate_ppo.py#L52). Specifically you can specify the split in the `config_env.DATASET.SPLIT` and it should work out of the box.

**Comment by edbeeching** [comment]
Ah excellent, thanks for your help.
