### ISSUE TITLE
one question about baseline 

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/habitat-challenge#11]
I know this challenge is over, but I want to have a try.
I try the script for local evaluation with rgb.pth, I follow the instruction without changes. I find the result I run is 0.4626, but the result from the leaderboard is 0.47. Is that the same model between the repo and the leaderboard?

**Comment by erikwijmans** [comment]
Those should be the same.  There is likely to be a small amount of variance as neither pytorch nor OpenGL guarantee exact reproduction across different different GPUs and versions.
