### ISSUE TITLE
Error downloading Dataset hm3d val

### ISSUE THREAD

**Issue by ricardmarsalcastan** [facebookresearch/habitat-challenge#115]
While downloading the validation dataset for the challenge, with this command,
`python -m habitat_sim.utils.datasets_download --username <***> --password <***> --uids hm3d_val`
 Our team keeps getting the following error:
```
** Resuming transfer from byte position 324
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1407  100  1407    0     0   5289      0 --:--:-- --:--:-- --:--:--  5289
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
Traceback (most recent call last):
  File "/opt/conda/envs/habitat-test/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/habitat-test/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/habitat-test/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 688, in <module>
    main(sys.argv[1:])
  File "/opt/conda/envs/habitat-test/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 683, in main
    uid, data_path, args.username, args.password, replace
  File "/opt/conda/envs/habitat-test/lib/python3.7/site-packages/habitat_sim/utils/datasets_download.py", line 520, in download_and_place
    with tarfile.open(data_path + package_name, "r:*") as tar_ref:
  File "/opt/conda/envs/habitat-test/lib/python3.7/tarfile.py", line 1580, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
The data folder appears like the following:
![image](https://user-images.githubusercontent.com/12833221/169027549-919fe8d2-4c25-4e40-8bd3-0bbea7837d0a.png)

We know the api key works because we are able to download the example dataset and in a previous machine the training dataset, but we can't do the validation anywhere. It looks like it can't extract the contents downloaded. Any ideas on how to proceed?
Thank you!

**Comment by anavuongdin** [comment]
Dear author @aclegg3 and @ricardmarsalcastan, I am currently encountering this problem, can you please give me some advice for solving this issue? Many thanks in advance!

**Comment by ykarmesh** [comment]
@anavuongdin I am able to download the data on my end. Can you recheck the `username` and `password` that you are using?

**Comment by anavuongdin** [comment]
I used the API tokens followed by the guide in Step 5 in https://github.com/facebookresearch/habitat-challenge#local-evaluation
Could you explain what possible errors had occurred? Thank you!

**Comment by ykarmesh** [comment]
Are you getting the exact same error as above? Can you try to delete any previous files that were downloaded and start fresh. It could be that the old files were problematic and now the downloader is trying to resume from that.

**Comment by anavuongdin** [comment]
Thank you for your replies, I managed to fix this, this problem may be due to the access to data was not processed. After having been processed, it works.
