### ISSUE TITLE
Changes between Challenge 2021 and Challenge 2022

### ISSUE THREAD

**Issue by AgentEXPL** [facebookresearch/habitat-challenge#116]
A new dataset called [HM3D-Semantics v0.1](https://aihabitat.org/datasets/hm3d-semantics/) is used in ObjectNav Challenge 2022.
Compared with the old dataset used in Challenge 2021, whether the number index indicating the category of object is changed in the new dataset?
Is there any methods/codes to check this.

**Comment by dhruvbatra** [comment]
@ykarmesh

**Comment by srama2512** [comment]
@AgentEXPL - Yes. The index has changed. You can check this in the episode datasets released for the corresponding challenges. In the `val/val.json.gz` dataset from challenge 2021 (with MP3D dataset), this was the mapping from objects to task ids:

```
"category_to_task_category_id": {"chair": 0, "table": 1, "picture": 2, "cabinet": 3, "cushion": 4, "sofa": 5, "bed": 6, "chest_of_drawers": 7, "plant": 8, "sink": 9, "toilet": 10, "stool": 11, "towel": 12, "tv_monitor": 13, "shower": 14, "bathtub": 15, "counter": 16, "fireplace": 17, "gym_equipment": 18, "seating": 19, "clothes": 20}
```

In the current 2022 challenge, this is the mapping from `val/val.json`:
```
"category_to_task_category_id": {"chair": 0, "bed": 1, "plant": 2, "toilet": 3, "tv_monitor": 4, "sofa": 5}
```

I hope this answers your question.
