### ISSUE TITLE
Issue about the execution time

### ISSUE THREAD

**Issue by Minzhao1995** [facebookresearch/habitat-challenge#117]
Hi, 

Recently the execution time of our submission sometimes exceeded the time limit. So we made several identical submissions to "val_mini". Most of them finished in one hour, but some cost more than 24 hours. Maybe there are some issues with some of the remote servers?

**Comment by dhruvbatra** [comment]
@ykarmesh

**Comment by ykarmesh** [comment]
@Minzhao1995 , This was an issue on the EvalAI side. Ram pushed a change to fix this. Closing this issue for now.
