### ISSUE TITLE
Use the ShortestPathSensor to obtain oracle actions for ObjNav and Question about the dataset

### ISSUE THREAD

**Issue by YicongHong** [facebookresearch/habitat-challenge#118]
Hi There,

I am working on the MP3D ObjNav task based on the 2021 challenge code. I would like to generate an oracle path to the target for each episode.

I understand that the target of ObjNav is not a single position, but it is defined as a list of viewpoints for objects of the same category, and the success criteria of ObjNav is distance to any of those viewpoints <0.1 meters. 
So for the ShortestPathSensor, I set the GOAL_RADIUS = 0.05, and set a fixed target for each episode as `episode.info['best_viewpoint_position']`, provided in the ObjNav dataset `scene_id.json.gz` file. I was expecting that the agent can reach the target viewpoint that is closest to the agent's initial position -- success the episode with SPL ~1.0. 

But when I ask the agent to follow the oracle actions for the episodes in the validation split, I obtained the following results:
> Average episode distance_to_goal: 0.1842
> Average episode success: 0.5417
> Average episode spl: 0.5127

I can see that the agent indeed moves very close to the target, but for many cases either the **oracle actions can't take the agent to within 0.1 meters**, or the **shortest path cannot be found**.

I am wondering if I did anything wrong. Could I please get some advices on how to obtain the oracle actions as expected?

Many thanks,
Yicong

**Comment by YicongHong** [comment]
Also, a question related to the MP3D ObjNav dataset: Each scene contains up to 50,000 episodes, but it seems that many of the episodes targeting the same object category have very close initial positions. 
For example in scan `VVfe2KiqLaN`, there are 14,865 episodes targeting "cushion". And for the episode `episode_id: 0`, there are 86 out of 14,865 other episodes that have a geodesic distance to `episode_id: 0` shorter than 0.25 meters. I am wondering, if my understanding about the success criteria is correct, then, aren't these episodes share very similar shortest path (and actions)? Aren't they "repetitive" training samples in the dataset?

**Comment by dhruvbatra** [comment]
@Skylion007

**Comment by Skylion007** [comment]
> For example in scan VVfe2KiqLaN, there are 14,865 episodes targeting "cushion". And for the episode episode_id: 0, there are 86 out of 14,865 other episodes that have a geodesic distance to episode_id: 0 shorter than 0.25 meters. I am wondering, if my understanding about the success criteria is correct, then, aren't these episodes share very similar shortest path (and actions)? Aren't they "repetitive" training samples in the dataset?

When generating the dataset, the criteria we used several criteria to create the objectnav datasets. We tried to remove trivial paths (ie. ones where you spawned in front of the object) and very long episodes. We also tried to ensure that they had some non-trivial shortest paths (ie. it wasn't just going in a straight line without obstacles to find it). However, some object annotations do not have very many instances per scene. Others may have a ton of instances per scene, but the shortest path is unlikely to be unique. (Imagine the case of finding the nearest bed, and all bedrooms are on the 2nd floor.  Unless you spawn somewhere on the 2nd floor, the bedroom closest to the staircase will always be the shortest path). There definitely are repetitive samples in the training set, and its one of the reasons why the training dataset is so large: so that models can encounter the rarer paths in the dataset as well. This issue is explored in our [THDA](https://openaccess.thecvf.com/content/ICCV2021/html/Maksymets_THDA_Treasure_Hunt_Data_Augmentation_for_Semantic_Navigation_ICCV_2021_paper.html) paper. The criteria for creating the datasets can be found in this [paper](https://arxiv.org/abs/2006.13171).

**Comment by Skylion007** [comment]
Odd that the oracle actions aren't working properly. We included this oracle paths to help with imitation learning, but they can easily be regenerated. Relatively minor changes like enable / disabling sliding could have invalidated the paths for some reason. You can easily regenerate the "oracles actions" by recalculating the paths using the ShortestPathFinder and plugging in the goal positions for the episodes. I would recommend trying that and seeing if the numbers improve.

**Comment by YicongHong** [comment]
Hello Aaron,

Thank you very much for your prompt and detailed reply. Yes, I am working on imitation learning for ObjNav. Just some follow up questions:

> For example in scan VVfe2KiqLaN, there are 14,865 episodes targeting "cushion". And for the episode episode_id: 0, there are 86 out of 14,865 other episodes that have a geodesic distance to episode_id: 0 shorter than 0.25 meters. I am wondering, if my understanding about the success criteria is correct, then, aren't these episodes share very similar shortest path (and actions)? Aren't they "repetitive" training samples in the dataset?

1. About the dataset and training. Just to clarify, in the example I given, if the 87 episodes have very close initial positions (<0.25m) and target at the same object category, and, **if I ask them to find the closest target as the shortest path**. Then, these shortest paths should be almost the same. Now, if I want to use these shortest paths for imitation learning, then I have 87 almost identical samples in the training data, isn't it?
2. Following the previous point, if I randomly assign target object positions (not the closest one) to these 87 episodes, and generate shortest paths. I am wondering how should the agent learn to not stop or not move to the closest target? For example, if the target is a bed in Bedroom B, but Bedroom A is closer than Bedroom B, and the agent has to pass Bedroom A to get to Bedroom B, what prevents the agent to not turn into Bedroom A? I feel like this will result in a very noisy sample. 

> You can easily regenerate the "oracles actions" by recalculating the paths using the ShortestPathFinder and plugging in the goal positions for the episodes.

Thanks for pointing out using the `episode.goals[k].position` instead of `episode.info['best_viewpoint_position']`, I agree that this should take the agent closer to the target viewpoints. I am using the standard agent configurations, e.g., no sliding. I would like to share some more results here (val split):
(1) Using the `episode.info['best_viewpoint_position']` to compute the oracle actions:

> Average episode distance_to_goal: 0.1842
> Average episode success: 0.5417
> Average episode spl: 0.5127

(2) Using a randomly object (I use the first one in the `episode.goals` list) position to compute the oracle actions:

> Average episode distance_to_goal: 1.4097            
> Average episode success: 0.7075                     
> Average episode spl: 0.4136                                                                                                      

(3) Using the closest object position (not the closest viewpoint) to compute the oracle actions:

> Average episode distance_to_goal: 0.4199
> Average episode success: 0.8296
> Average episode spl: 0.5985

It is pretty interesting to see that in (2), although SR increases a lot, the distance_to_goal in average is much larger. Not very sure why...  (3) is the best result I can get so far, I am very surprised by the boost comparing to (1), but again the distance becomes longer and the SPL is still quite low. Any ideas of these results?

So what I am thinking for imitation learning ObjNav is to filter out episodes in the training set that share the same target category and close initial positions, as well as removing episodes which shortest path cannot be from. In fact, I want to do student-forcing training so I need to compute oracle actions online (with the ShortestPathSensor and a fixed target position). May I get some comments/advices from you about this idea?

Many Thanks,
Yicong
