### ISSUE TITLE
Submission Error "No Such File" (val_mini.json.gz)

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/habitat-challenge#119]
Hi, thanks for your great effort on this challenge.

I counter a problem when submitting ```objectnav_submission:latest``` to evalai online benchmark. And the feedback error is listed as follows:
```
itat/core/benchmark.py", line 38, in __init__
    self._env = Env(config=config_env)
  File "/habitat-lab/habitat/core/env.py", line 78, in __init__
    id_dataset=config.DATASET.TYPE, config=config.DATASET
  File "/habitat-lab/habitat/datasets/registration.py", line 21, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/habitat-lab/habitat/datasets/object_nav/object_nav_dataset.py", line 74, in __init__
    super().__init__(config)
  File "/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 93, in __init__
    with gzip.open(datasetfile_path, "rt") as f:
  File "/opt/conda/envs/habitat/lib/python3.7/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/opt/conda/envs/habitat/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'habitat-challenge-data/objectgoal_hm3d/val_mini/val_mini.json.gz'
```
I also checked a similar [issue#76](https://github.com/facebookresearch/habitat-challenge/issues/76), and I believe it's not my case. Because I have successfully run the script  ```test_locally_objectnav_rgbd.sh``` on my own devices. The problem seems related to the dataset directory of the online benchmark. 

My submission ID is 210926. Appreciate any advice.

**Comment by devendrachaplot** [comment]
@ykarmesh

**Comment by ykarmesh** [comment]
@jzhzhang Are you facing this issue while following the README? Is it possible that you made any changes to the config file [here](https://github.com/facebookresearch/habitat-challenge/tree/main/configs)

**Comment by jzhzhang** [comment]
@ykarmesh Thanks for your help. The problem is solved by removing the cache of docker. I do not what exactly happened, but I'm glad the online benchmark works.
