### ISSUE TITLE
How can I evaluate without the docker?

### ISSUE THREAD

**Issue by hannahlee66** [facebookresearch/habitat-challenge#12]
Seems this code needs to build docker, how can we run it under the official habitat-api / habitat-sim environment without the docker?

Thanks a lot!

**Comment by hannahlee66** [comment]
@abhiskk

**Comment by mathfac** [comment]
You can run [Benchmark](https://github.com/facebookresearch/habitat-api/blob/master/examples/benchmark.py) from habitat-api with relevant config.
