### ISSUE TITLE
"standard_error" from habitat challenge 2021 test standard

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/habitat-challenge#120]
I submit my docker image to the evalai benchmark, but get the ``standard_error`.  There is no other information for me to investigate and the running hours are still smaller than 48 hours (151211.277366s). And I have successfully tested on the online mini val benchmark.

Here is the snapshot of the benchmark:
![image](https://user-images.githubusercontent.com/54199992/179398621-4da10348-24cf-4a71-9540-d49380e2ae26.png)

The submission ID is ```213080```.  Really appreciate your help.

**Comment by ykarmesh** [comment]
I see on EvalAI that you were able to run more experiments after this issue. Closing this issue for now.
