### ISSUE TITLE
Status is failed for test-standard phase but the status is finised for minival phase

### ISSUE THREAD

**Issue by AgentEXPL** [facebookresearch/habitat-challenge#121]
For my docker image, when it was submitted to the minival phase (habitat-objectnav-minival-2022-1615), the status could turned into "Finished" after 3885.399988s execution time. However, when the docker was submitted to the test-standard phase (habitat-objectnav-test-standard-2022-1615) or the challenge (habitat-objectnav-test-challenge-2022-1615 ) phase, the status turned into failed after some execution time. 
Please help to check the failed reason. My latest submission to test-standard phase is "evalai submission 216502".

**Comment by dhruvbatra** [comment]
@Ram81

**Comment by ykarmesh** [comment]
Hey @AgentEXPL this is the error I see:
