### ISSUE TITLE
visualization code of rearrangement task

### ISSUE THREAD

**Issue by kai-zhang-er** [facebookresearch/habitat-challenge#127]
Hello, could you please provide a visualization code for the rearrangement task? For example, during the local evaluation of the hierarchical baseline methods, how could we record the video so that we can find what happened to the robot? Thank you!

**Comment by ASzot** [comment]
Hello, absolutely. We provide visualization code in [Habitat Baselines](https://github.com/facebookresearch/habitat-lab/tree/main/habitat_baselines) (included with Habitat Lab). To visualize, run the evaluation in Habitat Baselines. The challenge evaluation script only gets the metrics. To evaluate in Habitat Baselines, run a similar command as the [DD-PPO training example](https://github.com/facebookresearch/habitat-challenge/tree/rearrangement-challenge-2022#dd-ppo-training-starter-code). Run something like the following commands (changing the `habitat-challenge` directory based on your setup):

* First enter the Habitat Lab directory.
* Next, make sure the skill policy weights are in the Habitat-Lab directory: `ln -s ../habitat-challenge/data/models data/models`
* Next, run evaluation in Habitat Baselines. To do so you will have to reference the data files in the challenge directory:
```
python -u habitat_baselines/run.py --exp-config habitat_baselines/config/rearrange/hab/tp_srl.yaml --run-type eval \
      BASE_TASK_CONFIG_PATH ../habitat-challenge/configs/tasks/rearrange_easy.local.rgbd.yaml \                        
      TASK_CONFIG.DATASET.DATA_PATH ../habitat-challenge/data/datasets/replica_cad/rearrange/v1/{split}/rearrange_easy.json.gz \
      TASK_CONFIG.DATASET.SCENES_DIR ../habitat-challenge/data/replica_cad/ \                          
      EVAL.SPLIT 'minival' \                                                                                           
      TASK_CONFIG.TASK.TASK_SPEC_BASE_PATH ../habitat-challenge/configs/pddl/ \                        
      TASK_CONFIG.SIMULATOR.DEBUG_RENDER True
```
`TASK_CONFIG.SIMULATOR.DEBUG_RENDER True` renders visualizations for the target object and goal position. Please let me know if you have any more questions.

**Comment by kai-zhang-er** [comment]
It works very well, thank you !
