### ISSUE TITLE
Slack Channel Link

### ISSUE THREAD

**Issue by ramadanomar** [facebookresearch/habitat-challenge#128]
Can we still join the competition? The slack channel link seems to be expired and requires an invite from a user that is already in. Thanks!

**Comment by dhruvbatra** [comment]
Anyone can join the competition at any point. Slack link has nothing to do with it. 

@Skylion007 can post the updated slack link.

**Comment by ASzot** [comment]
Hello, you can still join the competition. It goes until Oct 20, 2022. 

Here is the [correct slack link](https://join.slack.com/t/ai-habitat/shared_invite/zt-1dh17eqp1-GLi2quRBlMEgaRlF4irsCw). This is also now updated on the website. Thanks for pointing this out!

**Comment by ramadanomar** [comment]
Thanks!
