### ISSUE TITLE
How long does it takes to evaluate?

### ISSUE THREAD

**Issue by ricardmarsalcastan** [facebookresearch/habitat-challenge#129]
I submitted some code to the challenge in the Minival Phase and the Test-Challenge Phase one day ago and both of them still says 'running'. How long does it take to evaluate usually? Previous submits in the Minival Phase didn't take that long.
Thank you!

**Comment by ykarmesh** [comment]
Hi, since we are only 1 day away from the challenge deadline, there are a lot of submissions in the queue. Your jobs are also most probably in the queue waiting for the older evaluations to complete.
