### ISSUE TITLE
is that possible to submit for test standard or minival now

### ISSUE THREAD

**Issue by StOnEGiggity** [facebookresearch/habitat-challenge#13]
hi, I try to submit my result for minival, the status shows "submitted", but execution time and the result are None. I guess there may be some mistakes in my docker. So I follow Readme to submit the original agent and ppo agent. The status is "submitted" and others show "None".

My question is that is it possible to submit for test or minival. If so, any suggestions for my problems. 

Thanks a lot.

**Comment by dhruvbatra** [comment]
Very soon. We expect the EvalAI sites to open up in a week or so.

**Comment by AdventureO** [comment]
@dhruvbatra is the EvalAI sites open now for remote submissions ?

**Comment by dhruvbatra** [comment]
@StOnEGiggity @AdventureO -- EvalAI submissions are now live: 
https://evalai.cloudcv.org/web/challenges/challenge-page/580/overview

Apologies for the delay.
