### ISSUE TITLE
Submitting to 2021 MP3D ObjNav

### ISSUE THREAD

**Issue by ajzhai** [facebookresearch/habitat-challenge#134]
I would like to see my ObjNav agent's performance on the 2021 MP3D test-standard set for comparison with some older methods. However, none of my submissions to EvalAI are returning. Even on Minival, they have been on "Running" status for 72 hours. Is this due to a long queue, or are those servers no longer supported?

**Comment by ykarmesh** [comment]
Hey @ajzhai , we are investigating the reason for it. We will try to get back to you soon!

**Comment by ajzhai** [comment]
Looks like some of them finally returned recently. I guess the queue is just getting overloaded then?

**Comment by ykarmesh** [comment]
Yes, that is what we also found out on our end. Closing this issue for now!

**Comment by ajzhai** [comment]
Hey @ykarmesh, my previous submissions gave error message in the stderr when they failed, but my last one ran for a long time and failed with no error message at all. Do you know what the problem might be? My team name is Finding NIMO.
