### ISSUE TITLE
Abstract action space support

### ISSUE THREAD

**Issue by ishikasingh** [facebookresearch/habitat-challenge#135]
Thanks for releasing this super cool work!
I have a couple questions:

1. Does the current sim version support abstract action spaces like pick/place/open/close?
2. Is it possible to train hierarchical policies?
3. Is it feasible to define motion controllers to implement the above abstract actions - so it's possible to ablate the performance with ground truth low-level actions for plans defined in the abstract action space?

I am mainly looking for Q3, I think I found some information on Q1-2. 

Thanks!

**Comment by devendrachaplot** [comment]
This issue is more suitable for habitat-lab.

Please open an issue here:
https://github.com/facebookresearch/habitat-lab
