### ISSUE TITLE
Excuse me, I can't find 'branch challenge-2023' https://github.com/facebookresearch/habitat-lab.git

### ISSUE THREAD

**Issue by luhu65** [facebookresearch/habitat-challenge#146]

**Comment by ykarmesh** [comment]
challenge-2023 is a tag created from a particular branch. You can find it here: https://github.com/facebookresearch/habitat-lab/releases/tag/challenge-2023

You should be able to checkout a tag on your machine with the following command:
`git checkout challenge-2023`
