### ISSUE TITLE
Random Agent - Cannot set_action_space

### ISSUE THREAD

**Issue by klammecr** [facebookresearch/habitat-challenge#147]
Thanks for the amazing work! I was following the guide in this repository to get a random agent evaluating in the docker container, however, I am running into issues.

![image](https://user-images.githubusercontent.com/27089767/227248382-c7261444-935b-4f5c-be23-1e7f8ba4cef6.png)

The one thing I noticed is that there is not a 2023 branch for habitat-lab so I pulled down the main branch instead

**Comment by ykarmesh** [comment]
Main branch doesn't have these updates, so its reasonable that you are seeing this error. Check out Issue #146. Let me know if you are able to install habitat-lab from the challenge-2023 tag.

**Comment by klammecr** [comment]
I see I will try this and get back to you, must have missed this in my initial setup

**Comment by TsuTikgiau** [comment]
I have the same issue. I have tried to cd to /habitat-lab and do git checkout challenge-2023 when building the container, but the bug still exists. What is the correct way to do it?

**Comment by ykarmesh** [comment]
Hey @TsuTikgiau, Can you provide some details regarding how you are trying to build the container. I am able to checkout the `challenge-2023` tag inside the docker.

**Comment by klammecr** [comment]
I was able to get this working locally but not with the remote

**Comment by DumbMice** [comment]
I ran into the exact same problem, except that I am running commands directly within the docker environment provided by `fairembodied/habitat-challenge:habitat_navigation_2023_base_docker`:
![image](https://user-images.githubusercontent.com/28761810/229752873-b58227ad-96d5-441e-b8ef-d2daf003f020.png)
Looking at the docker file, I believe the habitat-lab repo cloned here is already tagged 2023-challenge.

I organize the file system and set environment variables as the docker file inside the habitat-challenge repo hints, 
![image](https://user-images.githubusercontent.com/28761810/229754517-cec6c84b-7f92-4852-9bbd-998bc539dac8.png)

and I got the error 
```
(habitat) root@habitat-7fdbdd8764-pk7xp:/# bash submission.sh --action_space velocity_controller
pybullet build time: Oct 28 2022 16:15:14
Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail




Traceback (most recent call last):
  File "agent.py", line 86, in <module>
    main()
  File "agent.py", line 82, in main
    challenge.submit(agent)
  File "/habitat-lab/habitat-lab/habitat/core/challenge.py", line 21, in submit
    metrics = super().evaluate(agent)
  File "/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 185, in evaluate
    return self.remote_evaluate(agent, num_episodes)
  File "/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 80, in remote_evaluate
    stub.set_action_space(
AttributeError: 'EnvironmentStub' object has no attribute 'set_action_space'
```
**And the error disappears if I run with** `export AGENT_EVALUATION_TYPE=local`
```2023-04-04 09:54:44,360 distance_to_goal: 4.741304381688436
2023-04-04 09:54:44,360 success: 0.0
2023-04-04 09:54:44,360 spl: 0.0
2023-04-04 09:54:44,360 soft_spl: 0.004107255869353769
2023-04-04 09:54:44,360 num_steps: 1.0
2023-04-04 09:54:44,360 collisions/count: 0.0
2023-04-04 09:54:44,360 collisions/is_collision: 0.0
2023-04-04 09:54:44,360 distance_to_goal_reward: 0.00788036584854126
```

**Comment by Ram81** [comment]
Hi @DumbMice ,

When testing the challenge submission docker locally you have to set `export AGENT_EVALUATION_TYPE=local`. The `remote` mode of evaluation is only supposed to be used for the submissions made to [EvalAI](https://eval.ai). Please use the [following scripts](https://github.com/facebookresearch/habitat-challenge/blob/main/scripts/test_local_objectnav.sh) to verify the local evaluation before you make a submission to EvalAI.

**Comment by ykarmesh** [comment]
To add to this -- we are working on solving issues with remote evaluation. We will post an update in the README when its ready. Keep doing local evaluation till then.

**Comment by ykarmesh** [comment]
This bug has been solved in the newest version of the `fairembodied/habitat-challenge:habitat_navigation_2023_base_docker`. Make sure you purge the old dockers so that you have the latest version, using the following command: `docker system prune -a`
