### ISSUE TITLE
Excuse me, I want to know the format of folders at all levels about hm3d_v0.2.

### ISSUE THREAD

**Issue by luhu65** [facebookresearch/habitat-challenge#148]

**Comment by ykarmesh** [comment]
Hi @luhu65, can you expand more on what you are looking for exactly?

**Comment by sjwcee** [comment]
> Hi @luhu65, can you expand more on what you are looking for exactly?

I have downloaded hm3d_ V0.2, but the file structure is incorrect. I want to know the file structure corresponding to hm3d_v0.2.
I just found the file structure corresponding hm3d (https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#loading-semantics-for-hm3d).

**Comment by srama2512** [comment]
@sjwcee  - The parent directory should be `data/scene_datasets/hm3d_v0.2`. The internal structure is the same as listed above. If you use the habitat-sim downloader, it should take care of the structuring for you.
