### ISSUE TITLE
HM3d for cvpr2023 challenge does not fit into memory

### ISSUE THREAD

**Issue by gianscarpe** [facebookresearch/habitat-challenge#150]
Hi! I'm trying to load hm3d scene in the environment by using habitat_baselines construct_envs, but even if I specify num_envs=1 my RAM (32GB) saturates and the process get killed. Is it expected? What are the requirements for hm3d with semantic?

I'm using habitat-lab from master and the most recent headless habitat-sim from conda.

Thank you,
Gianluca

**Comment by ykarmesh** [comment]
Hi @aclegg3, can you help @gianscarpe please.

**Comment by DumbMice** [comment]
I ran into the exact same problem, except that I am running commands directly within the docker environment provided by `fairembodied/habitat-challenge:habitat_navigation_2023_base_docker`:
![image](https://user-images.githubusercontent.com/28761810/229752873-b58227ad-96d5-441e-b8ef-d2daf003f020.png)
Looking at the docker file, I believe the habitat-lab repo cloned here is already tagged 2023-challenge.

I organize the file system and set environment variables as the docker file inside the habitat-challenge repo hints, 
![image](https://user-images.githubusercontent.com/28761810/229754517-cec6c84b-7f92-4852-9bbd-998bc539dac8.png)

and I got the error 
```
(habitat) root@habitat-7fdbdd8764-pk7xp:/# bash submission.sh --action_space velocity_controller
pybullet build time: Oct 28 2022 16:15:14
Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail




Traceback (most recent call last):
  File "agent.py", line 86, in <module>
    main()
  File "agent.py", line 82, in main
    challenge.submit(agent)
  File "/habitat-lab/habitat-lab/habitat/core/challenge.py", line 21, in submit
    metrics = super().evaluate(agent)
  File "/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 185, in evaluate
    return self.remote_evaluate(agent, num_episodes)
  File "/habitat-lab/habitat-lab/habitat/core/benchmark.py", line 80, in remote_evaluate
    stub.set_action_space(
AttributeError: 'EnvironmentStub' object has no attribute 'set_action_space'
```
**And the error disappears if I run with** `export AGENT_EVALUATION_TYPE=local`
```2023-04-04 09:54:44,360 distance_to_goal: 4.741304381688436
2023-04-04 09:54:44,360 success: 0.0
2023-04-04 09:54:44,360 spl: 0.0
2023-04-04 09:54:44,360 soft_spl: 0.004107255869353769
2023-04-04 09:54:44,360 num_steps: 1.0
2023-04-04 09:54:44,360 collisions/count: 0.0
2023-04-04 09:54:44,360 collisions/is_collision: 0.0
2023-04-04 09:54:44,360 distance_to_goal_reward: 0.00788036584854126
```

**Comment by ykarmesh** [comment]
We are working on solving some issues for uploading docker to EvalAI. Please use the local mode of evaluation till then.

**Comment by aclegg3** [comment]
Hey @gianscarpe, unfortunately the dataset is very large once unpacked into system memory. Locally, I see about 1GB per training scene with semantic annotations. Likely your system will not handle loading many of these scenes at the same time.

However, you can `close()` the simulator instance between calls to `reconfigure` to trigger memory release of the previous scene. Training will be slower because each scene will be re-loaded, but it won't consume more than ~1GB per worker process that way.
