### ISSUE TITLE
Issue with SSD File Naming in ResourceManager.cpp(355)::loadSemanticSceneDescriptor

### ISSUE THREAD

**Issue by jacklasts** [facebookresearch/habitat-challenge#156]
Description:
I encountered an issue with the SSD File Naming in the ResourceManager.cpp(355)::loadSemanticSceneDescriptor. When attempting to load the semantic scene descriptor, I received the following error message:

"[22:48:31:733810]:[Assets] ResourceManager.cpp(355)::loadSemanticSceneDescriptor : SSD File Naming Issue! Neither SceneInstanceAttributes-provided name : habitat-challenge-data/data/scene_datasets/hm3d_v0.2/minival/00800-TEEsavR23oF/TEEsavR23oF.basis.scn nor constructed filename : habitat-challenge-data/data/scene_datasets/hm3d_v0.2/minival/00800-TEEsavR23oF/info_semantic.json exist on disk."

It seems that neither the SceneInstanceAttributes-provided name nor the constructed filename exist on the disk. Can someone please help me resolve this issue?

I have provided a screenshot of my dataset file structure.
![ss](https://user-images.githubusercontent.com/128979106/230123910-b9b7253d-3949-4d97-b596-d56efe970bd1.jpg)

Thank you.

**Comment by aclegg3** [comment]
Hey @jacklasts, this issue looks like a problem with the SceneDataset config you are using.

In each folder (train, minival, val) there are multiple `.scene_dataset_config.json` files.
To use semantic annotations you should be loading from `hm3d_annotated_minival_basis.scene_dataset_config.json`. In general the `hm3d_annotated` prefix indicates that semantics are properly linked.

The error you see here is a generic simulator error for paths it tries to find, but it really should be loading `TEEsavR23oF.semantic.txt` in this case. The SceneDataset config sets up the paths for this.
