### ISSUE TITLE
DDPPO training seems stuck on loading, unsure if training is progressing

### ISSUE THREAD

**Issue by jacklasts** [facebookresearch/habitat-challenge#157]
I'm experiencing an issue where my DDPPO training appears to be stuck on loading and I'm unsure if the training is actually progressing. I've attached a screenshot of my nvidia-smi output as well as the repeated command line prompt for reference.

I tried to load 24 scenes. By the way, do you have any references if I want to train DDPPO on multiple GPUs?

Any help on resolving this issue would be greatly appreciated. Thank you!

![2023-04-05 23-13-20](https://user-images.githubusercontent.com/128979106/230126203-d10f56d7-404b-400b-9cd5-fe8d688c9e30.jpg)
![20230405231832](https://user-images.githubusercontent.com/128979106/230126565-660e9758-ee76-4a58-941a-2a3ef7c6acf3.jpg)

**Comment by ykarmesh** [comment]
The code only prints log after every 10 policy updates. Most probably it hasn't completed 10 updates by the time you posted this update. You can reduce the logging frequency by adding the following argument to the command that you run.
`habitat_baselines.log_interval=1"

Regarding multi-node training, you can find some information [here](https://github.com/facebookresearch/habitat-lab/tree/main/habitat-baselines/habitat_baselines/rl/ddppo#running).
