### ISSUE TITLE
Waypoint controller

### ISSUE THREAD

**Issue by morpheus1820** [facebookresearch/habitat-challenge#160]
Hi, I cannot understand how to use the waypoint controller (or whether it is implemented yet). Is there an example on how to use it?

**Comment by ykarmesh** [comment]
Hey @morpheus1820, the waypoint controller is implemented [here](https://github.com/facebookresearch/habitat-lab/blob/7a96559b09abfa060e063b4afa248aa7229c8a2d/habitat-lab/habitat/tasks/nav/nav.py#L1532). To use the waypoint controller, you need to change the action space of the agent [here](https://github.com/facebookresearch/habitat-challenge/blob/0663aecb2635c8ebae3072f9a95233a896861de6/configs/habitat/task/objectnav_v2_challenge.yaml#L3)  to waypoint_controller. The waypoint_controller config is defined [here](https://github.com/facebookresearch/habitat-lab/blob/7a96559b09abfa060e063b4afa248aa7229c8a2d/habitat-lab/habitat/config/habitat/task/actions/waypoint_controller.yaml). Note: the waypoint controller uses a continuous action space so we need to let the policy know that it should be predicting continuous action outputs by passing the following argument to the policy:
```
habitat_baselines.rl.policy.action_distribution_type=categorical
```

**Comment by morpheus1820** [comment]
Thank you, that solves it!
