### ISSUE TITLE
about agent config

### ISSUE THREAD

**Issue by KarelZhang** [facebookresearch/habitat-challenge#162]
The agent config is a little different from challenge 2022, such as the HFOV and the agent height. So if it is ok that I change the agent height, sensor resolution,hfov in challenge 2023?

**Comment by dhruvbatra** [comment]
You can do whatever you'd like at training time. For evaluation (on minival, val, test), we will use the Stretch configs (and no, those cannot be changed for 2023).

**Comment by KarelZhang** [comment]
OK, got it. Thanks a lot.

**Comment by KarelZhang** [comment]
OK, got it. Thank you, Dhruv!
