### ISSUE TITLE
Can not run pretrained weights of ObjectNav

### ISSUE THREAD

**Issue by elicassion** [facebookresearch/habitat-challenge#167]
Hi,

I'm trying to run the pretrained weights from `https://dl.fbaipublicfiles.com/habitat/data/baselines/v1/objectnav_v2_baseline_habitat_navigation_challenge_2023.pth` but getting:

```
RuntimeError: Error(s) in loading state_dict for PPO:
        Missing key(s) in state_dict: "actor_critic.net.prev_action_embedding.bias", "actor_critic.action_distribution.mu_maybe_std.weight", "actor_critic.action_distribution.mu_maybe_std.bias".
        Unexpected key(s) in state_dict: "actor_critic.action_distribution.linear.weight", "actor_critic.action_distribution.linear.bias".
        size mismatch for actor_critic.net.prev_action_embedding.weight: copying a param with shape torch.Size([7, 32]) from checkpoint, the shape in current model is torch.Size([32, 6]).
```

The running script I am using is 
```
python -u -m habitat_baselines.run \
    --config-name="ddppo_objectnav_v2_hm3d_stretch.yaml" \
    habitat_baselines.evaluate=True \
    habitat_baselines.eval_ckpt_path_dir="data/pretrained_checkpoints" \
    habitat.dataset.split=val \
```
which is specified at [starter-code](https://github.com/facebookresearch/habitat-challenge/tree/e39cbc31ae47f81a59ed606cd62d4ab7bb79f140#objectnavimagenav-baselines-and-dd-ppo-training-starter-code)

**Comment by ykarmesh** [comment]
We have provided you with the discrete action agent but it looks like you aren't passing config params required to use the agent to the model. Please take a look [here](https://github.com/facebookresearch/habitat-challenge/blob/e39cbc31ae47f81a59ed606cd62d4ab7bb79f140/docker/ObjectNav_ddppo_baseline.Dockerfile#L21-L27). These are the set of configs that we are passing to get the discrete action agent working:
```
    bash submission.sh \
    --model-path demo.ckpt.pth \
    --input-type rgbd \
    --task objectnav \
    --action_space discrete_waypoint_controller \
    --task-config configs/ddppo_objectnav_v2_hm3d_stretch.yaml \
    habitat_baselines.rl.policy.action_distribution_type=categorical \
    habitat_baselines.load_resume_state_config=True" \
```

**Comment by elicassion** [comment]
Thanks! Yes it was the action space problem and it works now. Sorry for the late reply.

**Comment by etri-jeon0123** [comment]
> We have provided you with the discrete action agent but it looks like you aren't passing config params required to use the agent to the model. Please take a look [here](https://github.com/facebookresearch/habitat-challenge/blob/e39cbc31ae47f81a59ed606cd62d4ab7bb79f140/docker/ObjectNav_ddppo_baseline.Dockerfile#L21-L27). These are the set of configs that we are passing to get the discrete action agent working:
> 
> ```
>     bash submission.sh \
>     --model-path demo.ckpt.pth \
>     --input-type rgbd \
>     --task objectnav \
>     --action_space discrete_waypoint_controller \
>     --task-config configs/ddppo_objectnav_v2_hm3d_stretch.yaml \
>     habitat_baselines.rl.policy.action_distribution_type=categorical \
>     habitat_baselines.load_resume_state_config=True" \
> ```

Is the code above the code for full execution?
Can you share the code that runs the whole thing?

**Comment by etri-jeon0123** [comment]
> Thanks! Yes it was the action space problem and it works now. Sorry for the late reply.

How did you fix the error caused by the lack of **`"action_space_config"`**?
