### ISSUE TITLE
Could not submit a docker at EvalAI page

### ISSUE THREAD

**Issue by alstar8** [facebookresearch/habitat-challenge#172]
Hi! I tried to push my docker submission at Habitat Challenge 2023 in EvalAI platform and every time got an error "Error: None" Tried every track and even 2022 year Challenge, also tried to submit from different servers and always get the same. My docker push command not even started to upload. EvalAI installed from pip without errors, init with my token goes without errors. Can someone help with that, please? Maybe there are common ways to debug it or there is some advice.

**Comment by Ram81** [comment]
@alstar8 can you please login again from EvalAI CLI and set the token using `evalai set_token <auth_token>` cli command and try again?

**Comment by alstar8** [comment]
@Ram81 Did not help, same Error: None again, and no other warnings or errors

**Comment by Ram81** [comment]
Hi @alstar8 ,

Can you confirm if `evalai challenges --participant` is working for you?

**Comment by alstar8** [comment]
Hi @Ram81, 
Resolved the issue by refreshing token at Eval.ai. Thank you for you help
