### ISSUE TITLE
The final list of the challenge phase

### ISSUE THREAD

**Issue by boboofan** [facebookresearch/habitat-challenge#181]
Until now, the CVPR workshop has been successfully held. When will the final list of the challenge phase be announced?

**Comment by KarelZhang** [comment]
I am waiting for it too

**Comment by april-zmx** [comment]
Me too.

**Comment by devendrachaplot** [comment]
The Test-Challenge Leaderboards are now visible on the EvalAI Challenge page:
https://eval.ai/web/challenges/challenge-page/1992/overview
