### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by dhruvbatra** [facebookresearch/habitat-challenge#19]
Our instructions say: 
> a) PoinNav: Download Gibson scenes used for Habitat Challenge. Accept terms here and select the download corresponding to “Habitat Challenge Data for Gibson (1.5 GB)“. Place this data in: habitat-challenge/habitat-challenge-data/gibson
> 
> b) ObjectNav: Download Matterport3D scenes used for Habitat Challenge here. Place this data in: habitat-challenge/habitat-challenge-data/mp3d

But our scripts are looking for `habitat-challenge/habitat-challenge-data/scene_datasets/mp3d`, as you can see from these errors: 

```bash
(base) dbatra@ubuntu-bionic-1:~/habitat-challenge$ ./test_locally_objectnav_rgbd.sh --docker-name my_submission
2020-03-05 03:15:30,744 Initializing dataset ObjectNav-v1
2020-03-05 03:15:30,776 initializing sim Sim-v0
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0305 03:15:31.245062    16 ResourceManager.cpp:84] Cannot load from file habitat-challenge-data/scene_datasets/mp3d/pLe4wQe7qrG/pLe4wQe7qrG.glb
E0305 03:15:31.249548    16 Simulator.cpp:106] cannot load habitat-challenge-data/scene_datasets/mp3d/pLe4wQe7qrG/pLe4wQe7qrG.glb
```

If I create appropriate symlinks, this error goes away: 
```bash
(base) dbatra@ubuntu-bionic-1:~/habitat-challenge$ ./test_locally_objectnav_rgbd.sh --docker-name my_submission
2020-03-05 03:36:44,704 Initializing dataset ObjectNav-v1
2020-03-05 03:36:44,733 initializing sim Sim-v0
2020-03-05 03:36:48,449 Initializing task ObjectNav-v1
2020-03-05 03:36:49,552 distance_to_goal: 5.235198982556661
2020-03-05 03:36:49,552 spl: 0.0
```

But we should fix this by checking for the dataset in the path we say it should be in.

**Comment by mathfac** [comment]
Should be unified now with [the change](https://github.com/facebookresearch/habitat-challenge/commit/03133621f0798bb33365d87daac23adb1a6c72c8).  
Relative path `habitat-challenge-data/data/scene_datasets/*` was chosen because if someone works on Habitat most probably already has `data` folder of specific hierarchy.

**Comment by mathfac** [comment]
Sorry, missed when this issue was opened.

**Comment by dhruvbatra** [comment]
Ok. 

But can we shorten the hierarchy? 

From `habitat-challenge-data/data/scene_datasets/*` to `habitat-challenge-data/scene_datasets/*`

**Comment by mathfac** [comment]
`habitat-challenge-data` folder isn't empty in our challenge repo. Therefore, symlink `habitat-challenge-data -> data` is difficult to use. `data` folder hierarchy 
is advised from [README habitat-api](url) repo.

We can add `mkdir -p habitat-challenge-data/data/scene_datasets` command to the README or if it looks cleaner switch to `habitat-challenge-data/mp3d` and `habitat-challenge-data/gibson` and then each participant will symlink each dataset.

**Comment by dhruvbatra** [comment]
Ah, makes sense. Let's keep this hierarchy for now. Closing.
