### ISSUE TITLE
submission phase

### ISSUE THREAD

**Issue by DejaVu2** [facebookresearch/habitat-challenge#2]
May i ask when does the submission phase go live

**Comment by abhiskk** [comment]
Hi, thanks for the interest. The submission phase should go live in ~7 days.

**Comment by DejaVu2** [comment]
Hi @abhiskk Thanks for your reply

**Comment by abhiskk** [comment]
@DejaVu2 the challenge has gone live, you can find more information here: https://aihabitat.org/challenge/
