### ISSUE TITLE
Evaluation time-limits

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-challenge#30]
How strictly will the model evaluation time be taken into consideration? I can imagine some models taking several hours rather than 30 minutes to complete 1000+ episodes.

**Comment by dhruvbatra** [comment]
Yes, we are aware. To be fully transparent, our own baselines aren't finishing in 30 min right now (and we are actively working on making things faster; but that shouldn't affect accuracy or any work already done by participants). We will be changing that part in the README. 

CC: @abhiskk

**Comment by srama2512** [comment]
Understood. Thank you. Some simple benchmarks showing how fast the default baselines are on the test server may be useful as well.

**Comment by dhruvbatra** [comment]
README updated. Closing issue for now.
