### ISSUE TITLE
About online evaluations

### ISSUE THREAD

**Issue by qweas120** [facebookresearch/habitat-challenge#31]
I submitted a docker image to the val_mini phase and test_standard phase a few hours ago. 

It ran well locally on val_mini, but the server doesn't have any result yet for both phases. What may cause the problem?

BTW, do the submissions wait in a pending queue for evaluation or be evaluated immediately?

Thanks

**Comment by RishabhJain2018** [comment]
Hi @qweas120,

> It ran well locally on val_mini, but the server doesn't have any result yet for both phases. What may cause the problem?

All the submissions to the challenge are evaluated now and the results/failure error will be present under "My Submissions" Tab on EvalAI.

> BTW, do the submissions wait in a pending queue for evaluation or be evaluated immediately?
 
The submissions wait in a queue for a few mins and then get evaluated.

**Comment by qweas120** [comment]
Thanks, I just received the output. It seems that the submissions were waiting in the queue for hours.
