### ISSUE TITLE
Is the turn angle supposed to be 30 degrees? 

### ISSUE THREAD

**Issue by akshay-krishnan** [facebookresearch/habitat-challenge#35]
Hi

Based on [the paper](https://arxiv.org/pdf/1912.06321.pdf), I understand that the turn_angle for the agent has been changed to 30 degrees in 2020? 
Why has this not been updated in the [pointnav config file](https://github.com/facebookresearch/habitat-challenge/blob/master/configs/challenge_pointnav2020.local.rgbd.yaml) or [the default config](https://github.com/facebookresearch/habitat-api/blob/habitat-challenge-2020/habitat/config/default.py)? Is there another configuration that I am missing?

**Comment by mathfac** [comment]
@akshay-krishnan, thank you for flagging this. That was a mistake on our end that we are going to fix.

**Comment by mathfac** [comment]
https://github.com/facebookresearch/habitat-challenge/pull/36 that address the issue.
