### ISSUE TITLE
Failed to build DD-PPO docker

### ISSUE THREAD

**Issue by AdventureO** [facebookresearch/habitat-challenge#37]
Just wanted to make initial submission with DD-PPO file without own training.

After running command:
```docker build . --file Pointnav_DDPPO_Baseline.Dockerfile -t pointnav_submission``` 
get an error:
```ADD failed: stat /var/lib/docker/tmp/docker-builder885297584/demo.ckpt.pth: no such file or directory```

Where can I find ```demo.ckpt.pth``` file for initial submission ?

**Comment by Skylion007** [comment]
That is going to the the trained ckpt file from the DDPPO. We are currently retraining our baselines to fix the bug resolved in #36 and will update it with the model soon. In the mean time, feel free to train your own DD-PPO models and they should work.

**Comment by Skylion007** [comment]
https://github.com/facebookresearch/habitat-challenge/pull/38 will be merged shortly and has a download link for our baseline model in the ReadMe.
