### ISSUE TITLE
Clarification needed regarding the submission deadline

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-challenge#44]
Is it sufficient for our final models to be under submission before the deadline, or should they have strictly finished evaluating before the deadline?

**Comment by mathfac** [comment]
@srama2512 thank you for the question. The submission is fine, but I would advice to submit a working earlier submission earlier and improve it to avoid last minute error.

**Comment by srama2512** [comment]
Got it. I just wanted to make sure the cut-off criteria were clear. Thanks.

**Comment by karkuspeter** [comment]
what is the cut-off time for submission (including timezone)?

**Comment by dhruvbatra** [comment]
The deadline is May 31, 2020 11:59:59 PM PST. That's what I see on EvalAI (I am in PT). 

+730 in your message above is likely indicating your timezone.
