### ISSUE TITLE
Clarifications about the challenge submission

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-challenge#48]
Hi,

I have submitted a model to the test-challenge track. 
- The status is "Submitted". What exactly does that mean? 
- How do we know that the test challenge evaluation succeeded, and that things went as expected?
- Given that we have upto 5 submissions, how will the best results be selected? Is it automatically based on the maximum SPL score, or do we have to somehow choose the final model? 

Note: I am seeing the same "Submitted" status for the minival and test standard submissions. I am a bit concerned because I submitted one of the prior docker submissions using the aws link. I want to make sure this works as intended.

**Comment by dhruvbatra** [comment]
1. It means it's queued for evaluation. 
2. Once evaluated, you will be able to see Success vs Failure status on EvalAI (but not any of the metrics). 
3. Automatically; max SPL.

**Comment by dhruvbatra** [comment]
https://github.com/facebookresearch/habitat-challenge/commit/3cabfd2566d026a43756c67d1eb6af2689ef205d

**Comment by srama2512** [comment]
Great! Thank you for the clarification in the README.
