### ISSUE TITLE
Configuration clarifications

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-challenge#51]
I have a couple of questions regarding the configurations: 
- A new file has been added: `configs/challenge_pointnav2020_v2.local.rgbd.yaml` which has a different sensor orientation. What is this for? Should we re-train our agents with this new configuration?
- What is the config file `configs/challenge_pointnav2020.local.rgbd_test_scene.yaml` for? It is using `v1` data. Should it not be `v2`?

**Comment by dhruvbatra** [comment]
> challenge_pointnav2020_v2.local.rgbd.yaml

Ignore it. It's something we will use in the future (introduces a tilt of the camera downwards); nothing is changing for this ongoing challenge. 

> challenge_pointnav2020.local.rgbd_test_scene.yaml

CC: @mathfac @abhiskk

**Comment by mathfac** [comment]
> What is the config file configs/challenge_pointnav2020.local.rgbd_test_scene.yaml for? It is using v1 data. Should it not be v2?
`configs/challenge_pointnav2020.local.rgbd_test_scene.yaml` is for testing submission without downloading MP3D dataset on our example scene. And yes, you're right the episode should be regenerated  for PointNav v2 dataset. Will delete it to avoid confusions.
