### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/habitat-challenge#52]
I am getting the following error on both my minival and test-std submissions:
```
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 15.75 GiB total capacity; 146.35 MiB already allocated; 22.00 MiB free; 11.65 MiB cached)
```
Just to give context, my local runs take up < 4GB memory for evaluation. The above error also seems to suggest that only `146.35 + 22 + 11.65` MiB memory was available to begin with. Is it possible that multiple users are assigned to the same GPUs?

**Comment by srama2512** [comment]
Any ideas on why this is happening? Almost all of my submissions have been failing in the past two days.

**Comment by dhruvbatra** [comment]
We are looking into it and will get back to you. This isn't an issue with Habitat, but EvalAI backend. I'm working with that team.

**Comment by srama2512** [comment]
If it helps, the test challenge submissions do not have a problem.

**Comment by RishabhJain2018** [comment]
Hi @srama2512, Sorry for the inconvenience caused. We have fixed this issue.
Do you want us to re-submit all your Test Standard/Test Challenge Phase Submissions or do you want to try submitting it again?

**Comment by srama2512** [comment]
Hi Rishab,

No worries. Thank you for fixing this! Since one of my submissions got through yesterday night, I think it's fine.

**Comment by srama2512** [comment]
I just verified that new submissions are going through. I'll close this issue now. Thank you again for the quick response!
