### ISSUE TITLE
Option to terminate running submission

### ISSUE THREAD

**Issue by karkuspeter** [facebookresearch/habitat-challenge#53]
Hi, 

Is there an option to terminate a submission currently being executed?
If not, could you manually terminate all my 3 submissions in the test-std track under user name "karkus" or increase the max number of parallel submissions?

I believe the scripts are hanging because of an extra process i launch, and wont exit unless the container is terminated. 

thanks!

**Comment by mathfac** [comment]
@karkuspeter what is your team, track and phase?

**Comment by RishabhJain2018** [comment]
Hi @karkuspeter, We have canceled all your running submissions and you should be able to create new submissions.

Please close this issue if this resolves your query.

**Comment by karkuspeter** [comment]
Thank you!
