### ISSUE TITLE
Time limit clarifications

### ISSUE THREAD

**Issue by karkuspeter** [facebookresearch/habitat-challenge#54]
Hi, 

Few clarification questions about runtime limits for the pointnav task

- What is the time limit for test-standard and test-challenge phase? The README mentions 24 hours, but i have noticed in the logs "Timelimit for test-std, test-challenge track is 151200 seconds" (42 hours)
 
- What is the number of evaluation episodes?

- Unfortunately my solution is currently rather slow, taking around 2 minutes per episode on average. 2000 episodes would take around 66 hours. Is it possible to extend the time limit?

- I have also noticed that if my script does not terminate within the time limit there is no output generated and the submission is marked failed. Would it be possible to generate results, maybe treating any remaining episodes as failed?  I have done something like this in my script (always take stop action if total execution time is beyond limit), but this limits my runtime to a specified amount, and I cannot be sure how much extra time will be spent on loading remaining episodes

thank you

**Comment by abhiskk** [comment]
Hi @karkuspeter 

1. We have increase the timelimit to 42hrs to allow evaluation of submissions which take longer.
2. Unfortunately we will not be able to extend the timelimit for evaluating the submission, in relation to truncating the episodes we are not doing that, your submission should successfully run on all the episodes within the specified timelimit to be considered for the final submission. I know this is not ideal but we do not be consistent in our evaluation for all participants.

**Comment by karkuspeter** [comment]
Ok i think thats fair. Thanks for the answers
