### ISSUE TITLE
Cancelling submission to evalai

### ISSUE THREAD

**Issue by devendrachaplot** [facebookresearch/habitat-challenge#55]
Hi,
Is there any way to cancel a submission to evalai? I am not sure if our submission got uploaded correctly and would like to cancel and resubmit to make sure.

**Comment by mathfac** [comment]
Please, message us the details about the submission.

**Comment by devendrachaplot** [comment]
I did, thanks!

**Comment by karkuspeter** [comment]
Hi, I have just emailed you with a similar request. Thanks!
