### ISSUE TITLE
Remote evaluations fail

### ISSUE THREAD

**Issue by karkuspeter** [facebookresearch/habitat-challenge#62]
Hi, I have made a couple of remote submissions recently (pointnav test-std) but they all fail. I have seen two types of failure cases, both happened multiple times. 

1, script fails after a few hours, and it produces an stderr output with the following error:
```
Traceback (most recent call last):
  File "agent.py", line 172, in <module>
    main()
  File "agent.py", line 168, in main
    challenge.submit(agent)
  File "/habitat-api/habitat/core/challenge.py", line 19, in submit
    metrics = super().evaluate(agent)
  File "/habitat-api/habitat/core/benchmark.py", line 171, in evaluate
    return self.remote_evaluate(agent, num_episodes)
  File "/habitat-api/habitat/core/benchmark.py", line 103, in remote_evaluate
    SerializedEntity=pack_for_grpc(action)
  File "/opt/conda/envs/habitat/lib/python3.6/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/conda/envs/habitat/lib/python3.6/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1599858112.185563913","description":"Error received from peer ipv4:127.0.0.1:8085","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
```

2, the script fails after 42 hours and it produces empty stdout and stderr files.

**Comment by karkuspeter** [comment]
Update: I found that submissions finish successfully first (the evalai status is finished, the new entry shows up in the leaderboard), but after some time the status changes to failed (status is failed, execution time changes to timelimit, results file is replaced with an empty file, the entry disappears from the leaderboard). 

This looks like an issue with the remote evaluation setup. I suspect that in my case this has to do with my script using python multiprocessing. As a workaround i have tried to ensure new processes always exit gracefully, but so far this did not resolve the issue.

**Comment by dhruvbatra** [comment]
CC: @RishabhJain2018

**Comment by RishabhJain2018** [comment]
I'll look into this. Thanks, @karkuspeter for reporting it.
