### ISSUE TITLE
Are the 2021 competition fairembodied/habitat-challenge docker images all published? 

### ISSUE THREAD

**Issue by RemedialRobotics** [facebookresearch/habitat-challenge#68]
Troubleshooting why I could not run and try your 2021 docker images for the habitat-challenge today and it seems like they might not have been published yet on docker hub? Or am I missing something? I'm able to **docker pull fairembodied/habitat-challenge:latest** but trying to build from the dockerfiles and that tag causes errors. 

docker pull fairembodied/habitat-challenge:testing_2021_habitat_base_docker

Error response from daemon: manifest for fairembodied/habitat-challenge:testing_2021_habitat_base_docker not found: manifest unknown: manifest unknown

thanks.

**Comment by mathfac** [comment]
@RemedialRobotics thank you for the question. Can you try to pull it now?

**Comment by RemedialRobotics** [comment]
fairembodied/habitat-challenge:testing_2021_habitat_base_docker
works now, haven't had a chance yet test any other tags. thanks.

**Comment by dhruvbatra** [comment]
Glad this worked. Let us know if you run into any other problems. Look forward to seeing your submission :-).
