### ISSUE TITLE
EvalAI Submission Instructions

### ISSUE THREAD

**Issue by bucherb** [facebookresearch/habitat-challenge#72]
In the submission instructions it states that valid phases are: habitat21-{pointnav, objectnav}-{minival, test-std, test-ch}. However, on the eval.ai submission website, the submission phases are listed in the format: habitat-objectnav-minival-2021-802. 

When trying to submit with the github instructions, I get the error:

Error: Challenge phase with slug habitat21-objectnav-minival does not exist

When trying to submit with the phases listed in the eval.ai website, I get the error:

Error: Sorry, cannot accept submissions since challenge phase is not active

Note that I can successfully make 2020 minival submissions on eval.ai.

Are the correct phases activated? Also, what is the correct phase naming convention?

Thank you!

**Comment by dhruvbatra** [comment]
Sorry about that. We'll fix it. 

CC: @RishabhJain2018 @mathfac.

**Comment by bucherb** [comment]
Thank you!

**Comment by mathfac** [comment]
Hi @bucherb,
Thank you for letting us know we will fix the inconsistencies. As stated on [the challenge website](https://aihabitat.org/challenge/2021/#dates) the leaderboards will be open on the 1st of March.

**Comment by mathfac** [comment]
@bucherb leaderboards are live.
