### ISSUE TITLE
turn angle 30 degrees

### ISSUE THREAD

**Issue by giadefa** [facebookresearch/habitat-challenge#75]
The configuration files provided in configs/challenge_pointnav2021.local.rgbd.yaml has
TURN_ANGLE: 30
but previous baselines like the DD-PPO paper use 10 degrees. I assume that for this challenge we have to use 30 right? The evaluation is performed with the same parameters as in  configs/challenge_pointnav2021.local.rgbd.yaml ?

thanks

**Comment by dhruvbatra** [comment]
CC: @mathfac

**Comment by giadefa** [comment]
Any comment?

**Comment by erikwijmans** [comment]
Yes, the challenge is evaluated with 30 degrees.  We made this changed based on our experience with sim2real, the noise at 10 degrees is too much.

**Comment by mathfac** [comment]
As Erik said:
<img width="688" alt="Screen Shot 2021-03-19 at 12 52 11 PM" src="https://user-images.githubusercontent.com/877440/111835247-eeaf8000-88b1-11eb-9889-ae8b4931c893.png">
