### ISSUE TITLE
Category list of Task 2

### ISSUE THREAD

**Issue by zxwang96** [facebookresearch/habitat-challenge#78]
Hi,

As the description said there is a subset of the original MP3D category list that only contains 21 items. I was wondering if it is publicly accessible? If it is, where we can find it?

Thanks!

**Comment by mathfac** [comment]
Yes, sure.
First, the mapping between original MP3D category and ObjectNav categories is available in the episodes ObjectNav dataset file [here](https://github.com/facebookresearch/habitat-lab/blob/master/habitat/datasets/object_nav/object_nav_dataset.py#L30-L31):

```
    category_to_task_category_id: Dict[str, int]
    category_to_scene_annotation_category_id: Dict[str, int]
```

Second, the categories are listed in the paper[ ObjectNav Revisited: On Evaluation of Embodied Agents Navigating to Objects](https://arxiv.org/abs/2006.13171):
<img width="330" alt="Screen Shot 2021-04-08 at 2 08 34 PM" src="https://user-images.githubusercontent.com/877440/114096681-eaa0cd80-9873-11eb-9c00-fb34aec0621e.png">
