### ISSUE TITLE
API verison

### ISSUE THREAD

**Issue by zxwang96** [facebookresearch/habitat-challenge#79]
Hi,

I found the API of habitat-challenge is different from the current version habitat-lab, can you specify which branch or version of habitat-lab shall I install to use habitat-challenge?

Thanks,

**Comment by dhruvbatra** [comment]
CC: @mathfac

**Comment by mathfac** [comment]
@zxwang96 ,
That is `challenge-2021` branch.
`git clone --branch challenge-2021 https://github.com/facebookresearch/habitat-lab.git`
