### ISSUE TITLE
Submission failed without any trace

### ISSUE THREAD

**Issue by titardrew** [facebookresearch/habitat-challenge#8]
I have just tried to push my submission, however, soon (411.10 sec) I’ve got `"Submission Status: failed"`. It seems that log files (stderr and stdout, as well as, results) are empty. Is there anything I can do to get more information regarding to this failure to debug my submission?

And yes, I tested my container with `./test_locally_{}.sh`
To:` habitat19-rgbd-minival`

**(duplicate from eval forum)**

**Comment by abhiskk** [comment]
Thanks for reaching out, we resubmitted and re-evaluated your submission and it worked successfully, it should be visible on the leaderboard now.

**Comment by titardrew** [comment]
That is great, but I've just got the same again for my another submission :(

**Comment by abhiskk** [comment]
On it, checking now.

**Comment by abhiskk** [comment]
The submission was successful 👍

**Comment by titardrew** [comment]
Oh, thanks! I hope this is the last time I disturb you :)

**Comment by abhiskk** [comment]
No problem at all, please do ping if you face more troubles.

**Comment by titardrew** [comment]
@abhiskk Hello! Same here again, now on test-std split. (Although my last submission (minival) had been successfully evaluated)

**Comment by abhiskk** [comment]
Hi, there was an error while downloading your docker for the test submission, we use AWS backend for uploading/storing/downloading the dockers, looking into this and will get back to you soon.

**Comment by abhiskk** [comment]
The result has been updated now 🙂

**Comment by titardrew** [comment]
Hello @abhiskk ! Same here again :( on rgbd-test-std

**Comment by titardrew** [comment]
Thanks a lot @abhiskk and all guys supporting this great challenge! It got a lot of fun and knowledge participating it, and I hope to see further iterations of this and other rl contests. Very curious to see how the `habitat-api` will look like at that time. I think it is time to close this issue.

**Comment by erikwijmans** [comment]
Glad you had fun participating!  If you are planning to attend CVPR, feel free to come say hi at the workshop.  If you aren't attending CVPR, hopefully you'll cross paths with at least some of us at a conference in the future!

**Comment by abhiskk** [comment]
Thanks for participating @titardrew , with regards to your previous comment about the issue on submission, we re-evaluated it and it was successful. I will reach out if needed. 

If you are attending CVPR do come and say hi 🙂
