### ISSUE TITLE
Docker installation with data softlink bug fixed?

### ISSUE THREAD

**Issue by lynl7130** [facebookresearch/habitat-challenge#80]
Hi there,

I found that in current ReadMe file local evaluation step 5, if a soft link is used and the suggested docker command is run, 
there would be an error message like this:
     
     2021-04-13 21:51:15,680 Initializing dataset ObjectNav-v1
     2021-04-13 21:51:15,710 initializing sim Sim-v0
     WARNING: Logging before InitGoogleLogging() is written to STDERR
     E0413 21:51:15.723701    17 StageAttributesManager.cpp:90] StageAttributesManager::registerObjectFinalize : Render asset template handle : habitat-challenge-data/data/scene_datasets/mp3d/x8F5xyUWy9e/x8F5xyUWy9e.glb specified in stage template with handle : habitat-challenge-data/data/scene_datasets/mp3d/x8F5xyUWy9e/x8F5xyUWy9e.glb does not correspond to any existing file or primitive render asset.  Aborting. 
      submission.sh: line 3:    17 Segmentation fault      (core dumped) python agent.py --evaluation $AGENT_EVALUATION_TYPE $@`

My fix was to change this line:

     -v $(realpath habitat-challenge-data/data/scene_datasets/mp3d) \

to

      -v $(realpath habitat-challenge-data/data/scene_datasets/mp3d):/habitat-challenge-data/data/scene_datasets/mp3d \

Not that familiar with Docker, so not sure whether this is a version problem or a bug.
Just want to post one solution!

Best,
Yiqing

**Comment by Skylark0924** [comment]
@lynl7130 That's awesome, this solved my problem!

**Comment by erikwijmans** [comment]
Likely a versioning thing as ` -v $(realpath habitat-challenge-data/data/scene_datasets/mp3d) \` worked at the time, but your update seems more portable!  I will update the readme

**Comment by Skylark0924** [comment]
@erikwijmans By the way, there is still a small problem in the readme.
![image](https://user-images.githubusercontent.com/24936522/117029809-99301500-ad31-11eb-9844-86a50bce7bdc.png)
The path is no longer working, it should be `/habitat_baselines/config/objectnav/ddppo_objectnav.yaml`

**Comment by mathfac** [comment]
@Skylark0924, the config should be the the relevant config from habitat-challenge directory. Therefore the fix would be to use `--exp-config ../habitat-challenge/configs/ddppo_${task}.yaml \`.
