### ISSUE TITLE
SPL agent path length calculation

### ISSUE THREAD

**Issue by frasermcghan** [facebookresearch/habitat-challenge#84]
How is the agent path length calculated in the SPL metric?

**Comment by mathfac** [comment]
Hi @frasermcghan,
Here is [the SPL code evaluation](https://github.com/facebookresearch/habitat-lab/blob/master/habitat/tasks/nav/nav.py#L543-L602).
The agent path length calculated as a sum of agent's position changes through the episode.

**Comment by mathfac** [comment]
@frasermcghan does it answer your question? Thank you!

**Comment by frasermcghan** [comment]
Yes, thank you!
