### ISSUE TITLE
Intermittent Failing/Finished Status of Identical EvalAI Submissions

### ISSUE THREAD

**Issue by bucherb** [facebookresearch/habitat-challenge#85]
I submitted to ObjectNav Test-Challenge. On EvalAI, the submission turned up as Cancelled almost immediately after submitting. The submission appeared again (about 10 min later) as a second submission on the site and was Running for 229350 sec. This job ultimately ended with the status Failed with blank result, std out and std err files. 

I submitted exactly the same container to the minival phase 1 time and the Test-Std phase 2 times. The minival submission completed successfully with results. The first Test-Std submission ended with a Failed status and blank result, std out and std err files. The second Test-Std submission completed successfully with results.

1. Do you have any ideas why these submissions could be intermittently Failing?
2. Is there a way I can try to get my submission to the Test-Challenge phase running without using my 6 total submissions since I have successfully run this submission on both of the other phases?

**Comment by Ram81** [comment]
@bucherb could you share the team handle? 

>Do you have any ideas why these submissions could be intermittently Failing?

There was a issue on our side which caused some submissions to fail.

>Is there a way I can try to get my submission to the Test-Challenge phase running without using my 6 total submissions since I have successfully run this submission on both of the other phases?

Yes, could you share the team name which you used to submit to the challenge?

**Comment by bucherb** [comment]
My team name is: Clueless-Wanderers. Thank you!

**Comment by Ram81** [comment]
@bucherb I have rerun the submission made on `May 27, 2021, 4:54 p.m.` which took `229350.23125s` that was submitted to Object Nav Test-Challenge Phase. You will see the previous submission as marked `Cancelled` and it won't be counted for the submission limit.

**Comment by bucherb** [comment]
Thank you! Should I wait until it's finished running without Failing to close this issue? Or just close now?

**Comment by bucherb** [comment]
This same issue happened again with my last submission to the Test-Challenge and Test-Standard phases.
