### ISSUE TITLE
"Challenge Phase is not active" error from ObjectNav minival 

### ISSUE THREAD

**Issue by bucherb** [facebookresearch/habitat-challenge#86]
When submitting to the minival phase with the command:

evalai push [image name] --phase habitat21-objectnav-minival --private

I get the error:

Error: Sorry, cannot accept submissions since challenge phase is not active

Use `evalai challenges` to fetch the active challenges.

Use `evalai challenge CHALLENGE phases` to fetch the active phases.

I can submit the same image to the Test-Standard and Test-Challenge phases.

**Comment by mathfac** [comment]
cc @RishabhJain2018

**Comment by mathfac** [comment]
Should be fixed now.
