### ISSUE TITLE
File **.scn does not exist error encountered when running DD-PPO script

### ISSUE THREAD

**Issue by shuishida** [facebookresearch/habitat-challenge#87]
Hello. I am trying to run the DD-PPO training script indicated here: https://github.com/facebookresearch/habitat-challenge#pointnavobjectnav-baselines-and-dd-ppo-training-starter-code 
I have download the Gibson dataset following the instructions and extract the dataset to folder `habitat-challenge/habitat-challenge-data/data/scene_datasets/gibson/` as indicated. I downloaded the 1.5 GB Habitat challenge dataset and it contained `.glb` and `.navmesh` files. However, when I tried running the [DD-PPO script](https://github.com/facebookresearch/habitat-lab/blob/master/habitat_baselines/rl/ddppo/single_node.sh) by
`sh habitat_baselines/rl/ddppo/single_node.sh` from the habitat-lab directory, it gave me errors saying that there aren't `.scn` files in the `habitat-challenge/habitat-challenge-data/data/scene_datasets/gibson/` directory. 

Does anyone know how I can resolve this issue or where to find these `.scn` files?

[Screenshot of error message](https://i.stack.imgur.com/eSGvv.png)

**Comment by erikwijmans** [comment]
That's a warning message that is a little too alarmist. Unless you are using the Gibson semantic annotations that message can be safely ignored (neither the pointnav nor objectnav challenge use those).

**Comment by shuishida** [comment]
Awesome, thank you!
