### ISSUE TITLE
Is time limit 42 or 48 hours?

### ISSUE THREAD

**Issue by haokuanluo** [facebookresearch/habitat-challenge#88]
The README says that the timelimit for objectnav is 48 hours, but my submission ended with "failure" status after 42 hours, and I noticed that in a previous issue there was a claim that the time limit is 42 hours. 

So what is the actual time limit? Is it 42 hours or 48 hours?

Thanks!

**Comment by srama2512** [comment]
I'm facing a similar issue. My submission ended with "failure" status after 42 hours.

**Comment by dhruvbatra** [comment]
Given the repeat issues, I suspect the README might have a typo and the limit may be 42 hours. I realize these pings are likely coming due to CVPR; unfortunately, we are unable to make any changes to the infra for the next few weeks.
