### ISSUE TITLE
Multi-level trajectory for objectnav task 

### ISSUE THREAD

**Issue by SgtVincent** [facebookresearch/habitat-challenge#91]
Hi! 

I noticed that there are multi-level scenes in the objectnav task dataset (e.g. XcA2TqTSSAj in matterport3D). Then I have the following questions: 
![Screenshot from 2022-02-22 16-31-54](https://user-images.githubusercontent.com/28901796/155165205-0cff475a-91e4-4451-9109-d76ce678db2c.png)

1) I wonder if, in the evaluation, an agent is required to navigate through a multi-level trajectory, i.e. an agent needs to learn to navigate through the staircases in the scene to reach the goal.   

2) If the answer is yes, what action does the agent need to execute to move on staircases? Is there any detailed documentation to describe this interaction?  e.g. If an agent executes "FORWARD" by 0.3m, how far does an agent move on the staircase? 0.3m on the horizontal (x-z) plane or 0.3m along the stair slope?   

Thanks!

**Comment by mathfac** [comment]
Hi @SgtVincent 
1. yes, for some episodes an agent is required to navigate through a multi-level trajectory.
2.  "what action does the agent need to execute to move on staircases?" Just Forward action on stairs is enough. Our navigation mesh is considered connected if height difference in under some threshold. 

`0.3m on the horizontal (x-z) plane or 0.3m along the stair slope?`
Here I will need help from @erikwijmans to comment on movement over the navmesh.

**Comment by erikwijmans** [comment]
I think it's 0.3m in the x-z plane, but I'm not 100% sure. We use a library called recast navigation for this and I don't know all the details of it.

**Comment by jzhzhang** [comment]
@SgtVincent Hi.  Just out of curiosity, what did you do to make the .glb file compatible with meshlab?
