### ISSUE TITLE
cannot find a link to EvalAI habitat 2022 challenge website

### ISSUE THREAD

**Issue by khy0809** [facebookresearch/habitat-challenge#92]
@aclegg3  @Skylion007 @RishabhJain2018 @dhruvbatra 
Hi, I'd like to participate in the habitat 2022 challenge. 
Where is the EvalAI challenge webpage of this year? I found a link in the readme but it only led me to last year's challenge website.

**Comment by dhruvbatra** [comment]
It's coming soon :-). We're waiting to land a few upstream things (e.g. HM3D-Semantic v0.1 into the matterport repository so participants have access to it).
