### ISSUE TITLE
What's the names of phases in Habitat 2022 Object Navigation Challenge?

### ISSUE THREAD

**Issue by Liangsanzhu** [facebookresearch/habitat-challenge#95]
Hello, I find the names of the phases below on [https://aihabitat.org/challenge/2022/](https://aihabitat.org/challenge/2022/):

> Valid challenge phases are habitat22-objectnav-{minival, test-std, test-ch}.

Then I try to submit, but none of them works:
>$ sudo evalai push objectnav_submission:latest --phase  habitat22-objectnav-minival

> Error: Challenge phase with slug habitat22-objectnav-minival does not exist

So what's the valid names of phases or Habitat 2022 Object Navigation Challenge? 
Or I just made wrong instructions?

Thanks a lot!

**Comment by devendrachaplot** [comment]
The valid challenge phases have been updated on the webpage.
